export const SHOW_COURSE = "SHOW_COURSE";
export const ADD_COURSE = "ADD_COURSE";
export const FETCHING_COURSE = "FETCHING_COURSE";
export const DELETE_COURSE = "DELETE_COURSE";


export const SHOW_CONTENT = "SHOW_CONTENT";
export const ADD_CONTENT = "ADD_CONTENT";
export const FETCHING_CONTENT = "FETCHING_CONTENT";

